#logging:
#  pattern:
#    file: "%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd HH:mm:ss.SSS}} ${LOG_LEVEL_PATTERN:-%5p} ${PID:- } [%36.36mdc{requestId}/%15.15mdc{trnId}|%6.6mdc{serialNn}]- [%t] %-40.40logger{39}: %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
#  file: '/var/log/rib/${name}.log'
#  path: '/var/log/rib/'
#
#logging.file.max-size: 1000MB
logging.level.org.springframework.security: DEBUG

management.endpoints.web.exposure.include: "*"
management:
  endpoint:
    metrics.enabled: true
    prometheus.enabled: true
    routes.enabled: true
    health:
      show-details: ALWAYS